server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_400
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
     ddl-auto: none
   show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db-changelog.xml

  freemarker:
    enabled: true
    template-loader-path: /WEB-INF/templates
    suffix: .ftl

  mail:
    host: smtp.gmail.com
    username: "***@gmail.com"
    password: "**** **** **** ****"
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000

mail:
  base-url: http://localhost:8080
  sender: Test Application
  from: ${spring.mail.username}
  subject: Please verify your account
  content: "Dear $name, please follow the link below to verify your account: <a href=$url>VERIFY</a>"

jwt:
  secret:
    access: and0LnNlY3JldC5hY2Nlc3Muand0LnNlY3JldC5hY2Nlc3M=
    refresh: and0LnNlY3JldC5yZWZyZXNoLmp3dC5zZWNyZXQucmVmcmVzaA==


logging:
  level:
    liquibase: INFO